package gui;

import dto.UtilizadorDTO;

/**
 * BemVindoGUI
 * Este JPanel contem uma mensagem para o utilizador, serve como Home.
 * 
 * @author joao
 */
public class BemVindoGUI extends javax.swing.JPanel {

    /**
     * Cria um novo form BemVindoGUI com um Objecto instanciado,
     * a partir de um utilizador que deu login, 
     * e define uma mensagem "Bem-vindo, " seguido do nome do utilizador.
     * @param utilizadorDTO Objeto instanciado do Utilizador que deu login.
     */
    public BemVindoGUI(UtilizadorDTO utilizadorDTO) {
        initComponents();
        
        lblBemVindo.setText("Bem-vindo, " + utilizadorDTO.getNome() + ".");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBemVindo = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(0, 0));

        lblBemVindo.setText("Bem-vindo");

        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMensagem.setText("<html>Gestor de Empresa.<br>Nesta aplicação pode gerir Serviços, Processos, Clientes e Funcionários de uma Empresa da área dos Eventos Culturais<br>Clique no menu para escolher uma opção.<html>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblMensagem;
    // End of variables declaration//GEN-END:variables
}
