package gui;

import dao.ClienteDAO;
import dao.ServicoDAO;
import dto.ServicoDTO;
import dto.ClienteDTO;
import enums.EstadoServico;
import java.math.BigDecimal;


import java.sql.SQLException;
import java.util.List;
import java.util.Objects;
import javax.swing.JOptionPane;
import myutils.TableFormatter;

/**
 * ServicosGUI
 * Este JPanel contém operações sobre Serviços.
 * 
 * @author joao
 */
public class ServicosGUI extends javax.swing.JPanel {

    /**
     * Creates new form ServicosGUI
     */
    public ServicosGUI() {
        initComponents();
        setupTable();
        loadDataSet();
        loadCbxClientes();
        clearCampos();
    }
    
    /**
     * Método que carrega informações para uma table.
     */
    public void loadDataSet() {
        try {
            ServicoDAO servicoDAO = new ServicoDAO();
            tblMain.setModel(servicoDAO.buildTableModel(servicoDAO.getQueryResult()));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void setupTable() {
        TableFormatter.formatTable(tblMain);
    }
    
    /**
     * Método que carrega informações da base de dados para uma table, dado um texto.
     * @param texto Texto para procurar
     */
    public void loadSearchData(String texto) {
        try {
            ServicoDAO servicoDAO = new ServicoDAO();
            tblMain.setModel(servicoDAO.buildTableModel(servicoDAO.getSearchResult(texto)));
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    /**
     * Método com ciclo foreach clientes de uma lista, para popular uma combobox
    */
    private void loadCbxClientes() {
        ClienteDAO clienteDAO = new ClienteDAO();
        List<ClienteDTO> clientesDTO = clienteDAO.getClientesDAO();
        for (ClienteDTO clienteDTO : clientesDTO) {
            cbxCliente.addItem(clienteDTO);
        }
    }
    
    /**
     * Método para limpar os campos de inserir inputs.
     */
    public void clearCampos() {
        txtDescricao.setText("");
        txtPreco.setText("");
        txtFiltrar.setText("");
        cbxCliente.setSelectedIndex(-1);
        cbxEstado.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPaneMain = new javax.swing.JScrollPane();
        tblMain = new javax.swing.JTable();
        txtFiltrar = new javax.swing.JTextField();
        lblFiltrar = new javax.swing.JLabel();
        jPanelServico = new javax.swing.JPanel();
        lblServico = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox<>();
        lblCliente = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        lblDescricao = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        lblPreco = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        btnRegistar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        tblMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMainMouseClicked(evt);
            }
        });
        jScrollPaneMain.setViewportView(tblMain);

        txtFiltrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltrarKeyReleased(evt);
            }
        });

        lblFiltrar.setText("Filtrar:");

        lblServico.setText("Serviço");

        lblCliente.setText("Cliente");

        lblDescricao.setText("Descrição");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ABERTO", "SEGUIMENTO", "CONCLUIDO", "CANCELADO" }));

        lblEstado.setText("Estado");

        lblPreco.setText("Preço");

        btnRegistar.setText("Registar");
        btnRegistar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelServicoLayout = new javax.swing.GroupLayout(jPanelServico);
        jPanelServico.setLayout(jPanelServicoLayout);
        jPanelServicoLayout.setHorizontalGroup(
            jPanelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelServicoLayout.createSequentialGroup()
                        .addComponent(lblServico)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelServicoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cbxCliente, javax.swing.GroupLayout.Alignment.TRAILING, 0, 184, Short.MAX_VALUE))
                            .addComponent(lblDescricao, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPreco, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelServicoLayout.setVerticalGroup(
            jPanelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServicoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblServico)
                .addGap(5, 5, 5)
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistar)
                .addGap(18, 18, 18)
                .addComponent(btnEditar)
                .addGap(59, 59, 59)
                .addComponent(btnCancelar)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFiltrar)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 569, Short.MAX_VALUE))
                            .addComponent(jScrollPaneMain))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblFiltrar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPaneMain, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        if (tblMain.getSelectedRow() < 0)
            JOptionPane.showMessageDialog(this, "Por favor selecione um Serviço.");
        else {
            if (txtDescricao.getText().isEmpty() || txtPreco.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos.");
            } else {
                ServicoDTO servicoDTO = new ServicoDTO();
                servicoDTO.setId((int) tblMain.getValueAt(tblMain.getSelectedRow(), 0));
                // sacar o id do cliente que esta na combobox
                ClienteDTO clienteDTO = (ClienteDTO) cbxCliente.getSelectedItem();
                if (clienteDTO != null) {
                    servicoDTO.setIdCliente(clienteDTO.getId());
                }
                servicoDTO.setDescricao(txtDescricao.getText());
                servicoDTO.setEstadoServico(EstadoServico.valueOf((String) cbxEstado.getSelectedItem()));
                servicoDTO.setPreco(BigDecimal.valueOf(Double.parseDouble(txtPreco.getText().replace(",", "."))));
                new ServicoDAO().editarServicoDAO(servicoDTO);
                loadDataSet();
                clearCampos();
            }
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnRegistarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistarActionPerformed
        if (txtDescricao.getText().isEmpty() || txtPreco.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor preencha todos os campos."); 
        } else {
            ServicoDTO servicoDTO = new ServicoDTO();
            // sacar o id do cliente que esta na combobox
            ClienteDTO clienteDTO = (ClienteDTO) cbxCliente.getSelectedItem();
            if (clienteDTO != null) {
                servicoDTO.setIdCliente(clienteDTO.getId());
            }
            servicoDTO.setDescricao(txtDescricao.getText());
            servicoDTO.setEstadoServico(EstadoServico.valueOf(Objects.requireNonNull(cbxEstado.getSelectedItem()).toString()));
            servicoDTO.setPreco(BigDecimal.valueOf(Double.parseDouble(txtPreco.getText().replace(",", "."))));
            new ServicoDAO().registarServicoDAO(servicoDTO);
            loadDataSet();
            clearCampos();
        }
    }//GEN-LAST:event_btnRegistarActionPerformed

    private void tblMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMainMouseClicked
        int linha = tblMain.getSelectedRow();
        int coluna = tblMain.getColumnCount();
        Object[] val = new Object[coluna];
        for (int i = 0; i < coluna; i++) {
            val[i] = tblMain.getValueAt(linha, i);
        }
        // Escolhe o cliente do servico selecionado na cbxCliente
        for (int i = 0; i < cbxCliente.getItemCount(); i++) {
            ClienteDTO clienteDTO = cbxCliente.getItemAt(i);
            if (clienteDTO.getNome().equals(val[1].toString())) {
                cbxCliente.setSelectedItem(clienteDTO);
                break;
            }
        } 
        txtDescricao.setText(val[2].toString());
        cbxEstado.setSelectedItem(val[3].toString().toUpperCase().replace(" ", "_").replace("Í", "I"));
        txtPreco.setText(val[4].toString());
    }//GEN-LAST:event_tblMainMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        clearCampos();
        loadDataSet();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtFiltrarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltrarKeyReleased
        String texto = txtFiltrar.getText();
        loadSearchData(texto);
    }//GEN-LAST:event_txtFiltrarKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnRegistar;
    private javax.swing.JComboBox<ClienteDTO> cbxCliente;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JPanel jPanelServico;
    private javax.swing.JScrollPane jScrollPaneMain;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblDescricao;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFiltrar;
    private javax.swing.JLabel lblPreco;
    private javax.swing.JLabel lblServico;
    private javax.swing.JTable tblMain;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtFiltrar;
    private javax.swing.JTextField txtPreco;
    // End of variables declaration//GEN-END:variables
}
